CREATE DATABASE IF NOT EXISTS resumatch_pro CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE resumatch_pro;

CREATE TABLE users (id BIGINT PRIMARY KEY AUTO_INCREMENT, full_name VARCHAR(100) NOT NULL, email VARCHAR(100) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL, phone VARCHAR(15), location VARCHAR(100), role ENUM('JOB_SEEKER','RECRUITER','RECRUITER_TEAM','ADMIN') NOT NULL, is_active BOOLEAN DEFAULT TRUE, is_email_verified BOOLEAN DEFAULT FALSE, last_login_at TIMESTAMP NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at TIMESTAMP NULL, INDEX idx_users_email (email), INDEX idx_users_role (role));

CREATE TABLE recruiter_profiles (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL UNIQUE, company_name VARCHAR(150) NOT NULL, company_email VARCHAR(100), industry VARCHAR(100), company_size VARCHAR(50), company_description TEXT, website VARCHAR(200), logo_url VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);

CREATE TABLE seeker_profiles (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL UNIQUE, headline VARCHAR(200), linkedin_url VARCHAR(200), portfolio_url VARCHAR(200), github_url VARCHAR(200), total_experience_years INT DEFAULT 0, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);

CREATE TABLE refresh_tokens (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, token VARCHAR(500) UNIQUE NOT NULL, expires_at TIMESTAMP NOT NULL, is_revoked BOOLEAN DEFAULT FALSE, device_info VARCHAR(300), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);

CREATE TABLE password_reset_tokens (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, token VARCHAR(255) UNIQUE NOT NULL, expires_at TIMESTAMP NOT NULL, is_used BOOLEAN DEFAULT FALSE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);

CREATE TABLE login_attempts (id BIGINT PRIMARY KEY AUTO_INCREMENT, email VARCHAR(100), ip_address VARCHAR(50), is_successful BOOLEAN, attempt_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE job_listings (id BIGINT PRIMARY KEY AUTO_INCREMENT, recruiter_id BIGINT NOT NULL, job_title VARCHAR(150) NOT NULL, job_description TEXT, required_skills TEXT, preferred_skills TEXT, ats_keywords TEXT, min_experience_years INT DEFAULT 0, education_requirement VARCHAR(200), job_type ENUM('FULL_TIME','PART_TIME','INTERNSHIP','CONTRACT') DEFAULT 'FULL_TIME', industry VARCHAR(100), location VARCHAR(150), is_remote BOOLEAN DEFAULT FALSE, salary_range VARCHAR(100), number_of_openings INT DEFAULT 1, application_deadline DATE, status ENUM('ACTIVE','CLOSED','DRAFT') DEFAULT 'ACTIVE', view_count INT DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at TIMESTAMP NULL, FOREIGN KEY (recruiter_id) REFERENCES users(id));

CREATE TABLE resumes (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, original_filename VARCHAR(255), stored_filename VARCHAR(255), file_path VARCHAR(500), file_type ENUM('PDF','DOCX') NOT NULL, file_size_kb BIGINT, extracted_text LONGTEXT, word_count INT, is_active BOOLEAN DEFAULT TRUE, upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP NULL, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);

CREATE TABLE applications (id BIGINT PRIMARY KEY AUTO_INCREMENT, job_seeker_id BIGINT NOT NULL, job_listing_id BIGINT NOT NULL, resume_id BIGINT NOT NULL, status ENUM('APPLIED','UNDER_REVIEW','SHORTLISTED','INTERVIEW_SCHEDULED','INTERVIEW_DONE','OFFERED','HIRED','REJECTED') DEFAULT 'APPLIED', recruiter_notes TEXT, applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (job_seeker_id) REFERENCES users(id), FOREIGN KEY (job_listing_id) REFERENCES job_listings(id), FOREIGN KEY (resume_id) REFERENCES resumes(id), UNIQUE KEY unique_application (job_seeker_id, job_listing_id));

CREATE TABLE resume_analysis (id BIGINT PRIMARY KEY AUTO_INCREMENT, application_id BIGINT NOT NULL, resume_id BIGINT NOT NULL, job_listing_id BIGINT NOT NULL, analysis_status ENUM('PROCESSING','COMPLETED','FAILED') DEFAULT 'PROCESSING', final_score INT, grade VARCHAR(5), grade_label VARCHAR(50), ats_status VARCHAR(50), extracted_skills TEXT, matched_keywords TEXT, missing_keywords TEXT, keyword_confidence_scores TEXT, skill_match_percentage INT, detected_action_verbs TEXT, weak_phrases_found TEXT, estimated_experience_years INT, experience_gap_years INT, measurable_achievements TEXT, detected_sections TEXT, missing_sections TEXT, contact_info_json TEXT, resume_word_count INT, education_detected VARCHAR(300), education_match_type VARCHAR(50), weak_areas TEXT, improvement_suggestions LONGTEXT, overall_feedback TEXT, analysis_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, processing_time_ms BIGINT, score_version INT DEFAULT 1, keyword_match_score INT, skill_relevance_score INT, experience_quality_score INT, achievements_score INT, formatting_score INT, education_match_score INT, FOREIGN KEY (application_id) REFERENCES applications(id), FOREIGN KEY (resume_id) REFERENCES resumes(id), FOREIGN KEY (job_listing_id) REFERENCES job_listings(id));

CREATE TABLE notifications (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, title VARCHAR(200) NOT NULL, message TEXT NOT NULL, type ENUM('APPLICATION_RECEIVED','STATUS_CHANGE','SHORTLISTED','REJECTED','INTERVIEW_SCHEDULED','JOB_MATCH','DEADLINE_REMINDER','SCORE_UPDATED','SYSTEM') NOT NULL, is_read BOOLEAN DEFAULT FALSE, redirect_url VARCHAR(300), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);

CREATE TABLE job_bookmarks (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, job_listing_id BIGINT NOT NULL, saved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY (job_listing_id) REFERENCES job_listings(id) ON DELETE CASCADE, UNIQUE KEY unique_bookmark (user_id, job_listing_id));

CREATE TABLE interview_schedules (id BIGINT PRIMARY KEY AUTO_INCREMENT, application_id BIGINT NOT NULL, scheduled_by BIGINT NOT NULL, interview_date DATETIME NOT NULL, duration_minutes INT DEFAULT 60, interview_mode ENUM('IN_PERSON','VIDEO','PHONE') DEFAULT 'VIDEO', location_or_link VARCHAR(500), notes TEXT, status ENUM('SCHEDULED','COMPLETED','CANCELLED','RESCHEDULED') DEFAULT 'SCHEDULED', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (application_id) REFERENCES applications(id), FOREIGN KEY (scheduled_by) REFERENCES users(id));

CREATE TABLE external_applications (id BIGINT PRIMARY KEY AUTO_INCREMENT, job_listing_id BIGINT NOT NULL, recruiter_id BIGINT NOT NULL, resume_file_path VARCHAR(500), original_filename VARCHAR(255), candidate_name_extracted VARCHAR(200), candidate_email_extracted VARCHAR(200), analysis_id BIGINT, uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (job_listing_id) REFERENCES job_listings(id), FOREIGN KEY (recruiter_id) REFERENCES users(id));

CREATE TABLE admin_audit_logs (id BIGINT PRIMARY KEY AUTO_INCREMENT, admin_id BIGINT NOT NULL, action VARCHAR(100) NOT NULL, target_type VARCHAR(50), target_id BIGINT, details TEXT, ip_address VARCHAR(50), timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (admin_id) REFERENCES users(id));

CREATE TABLE recruiter_teams (id BIGINT PRIMARY KEY AUTO_INCREMENT, company_owner_id BIGINT NOT NULL, member_user_id BIGINT NOT NULL, invited_by BIGINT NOT NULL, role VARCHAR(50) DEFAULT 'RECRUITER_TEAM', joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, is_active BOOLEAN DEFAULT TRUE, FOREIGN KEY (company_owner_id) REFERENCES users(id), FOREIGN KEY (member_user_id) REFERENCES users(id), FOREIGN KEY (invited_by) REFERENCES users(id), UNIQUE KEY unique_team_member (company_owner_id, member_user_id));

INSERT INTO users (full_name, email, password, phone, role, is_active, is_email_verified) VALUES ('System Admin', 'admin@resumatch.pro', '$2a$12$LJ3m4ys3Lg3YOCwKkp/wBe0ZF7qNINEbKaNfFkTC5qAXJSGHFcg1u', '9999999999', 'ADMIN', TRUE, TRUE);
